use serde::{Deserialize, Serialize};

use crate::{
    ids::{PaneId, TabId, WorkspaceId},
    pane::PaneNode,
};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Workspace {
    pub id: WorkspaceId,
    /// User-visible workspace name. Names are generated by the dispatcher for
    /// new workspaces and can be explicitly renamed through a command.
    #[serde(default = "default_workspace_title")]
    pub title: String,
    pub tabs: Vec<TabId>,
    pub active_tab: Option<TabId>,
}

impl Workspace {
    /// Compatibility constructor used by older callers that did not provide a
    /// title. New application code should use `new_with_title`.
    pub fn new(id: WorkspaceId) -> Self {
        Self::new_with_title(id, default_workspace_title())
    }

    pub fn new_with_title(id: WorkspaceId, title: String) -> Self {
        Self {
            id,
            title,
            tabs: Vec::new(),
            active_tab: None,
        }
    }
}

fn default_workspace_title() -> String {
    "Workspace".to_owned()
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Tab {
    pub id: TabId,
    pub title: String,
    /// `Some` means the user (or an explicit command) pinned the title. An
    /// automatic title follows the foreground process of the active pane.
    #[serde(default)]
    pub title_override: Option<String>,
    pub root: PaneNode,
    pub active_pane: PaneId,
}

impl Tab {
    /// Compatibility constructor: an explicitly supplied title is considered
    /// intentional and therefore remains pinned.
    pub fn new(id: TabId, title: String, initial_pane: PaneId) -> Self {
        Self::new_with_title(id, title.clone(), initial_pane, Some(title))
    }

    pub fn new_auto(id: TabId, title: String, initial_pane: PaneId) -> Self {
        Self::new_with_title(id, title, initial_pane, None)
    }

    pub fn new_with_title(
        id: TabId,
        title: String,
        initial_pane: PaneId,
        title_override: Option<String>,
    ) -> Self {
        Self {
            id,
            title,
            title_override,
            root: PaneNode::leaf(initial_pane),
            active_pane: initial_pane,
        }
    }
}
