//! Minimal zsh integration injected at spawn time via `ZDOTDIR`.
//!
//! Water's bundled terminfo keeps the standard `clear` capability so
//! zle's Ctrl-L behaves classically (push the screen into scrollback,
//! redraw the prompt at the top). The "clear also erases scrollback"
//! behavior — the one users know from kitty-style setups — needs to be
//! attached to the `clear` *command* specifically, because a raw byte
//! stream cannot distinguish `/usr/bin/clear` from Ctrl-L: both emit the
//! same terminfo string. So the split is made in the shell, not in the
//! emulator: the wrapper ZDOTDIR sources the user's own startup files
//! first and then defines a `clear` function that appends the CSI 3 J
//! (erase scrollback) sequence. A user-defined `clear` always wins.
//!
//! The chain lives under the application support directory, is
//! regenerated on every Water launch, and is disabled by setting
//! `WATER_NO_SHELL_INTEGRATION` in the environment that launches Water.
//! Nested shells deliberately inherit the user's real ZDOTDIR back, so
//! they start plainly without the chain double-running.

use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;
use std::sync::OnceLock;

const MARKER_ENV: &str = "WATER_NO_SHELL_INTEGRATION";
const USER_ZDOTDIR_ENV: &str = "__WATER_USER_ZDOTDIR";

/// Environment overrides for a child shell. Only zsh gets the
/// integration; every other program spawns untouched.
pub(crate) fn child_environment(program: &str) -> HashMap<String, String> {
    if !is_zsh(program) || std::env::var_os(MARKER_ENV).is_some() {
        return HashMap::new();
    }
    let Some(directory) = integration_directory() else {
        return HashMap::new();
    };
    let user_zdotdir = std::env::var_os("ZDOTDIR")
        .or_else(|| std::env::var_os("HOME"))
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."));
    let mut env = HashMap::new();
    env.insert(
        "ZDOTDIR".to_owned(),
        directory.to_string_lossy().into_owned(),
    );
    env.insert(
        USER_ZDOTDIR_ENV.to_owned(),
        user_zdotdir.to_string_lossy().into_owned(),
    );
    env
}

fn is_zsh(program: &str) -> bool {
    std::path::Path::new(program)
        .file_name()
        .and_then(|name| name.to_str())
        .map(|name| name.trim_start_matches('-'))
        .is_some_and(|name| name == "zsh")
}

fn integration_directory() -> Option<PathBuf> {
    static READY: OnceLock<Option<PathBuf>> = OnceLock::new();
    READY
        .get_or_init(|| {
            let home = std::env::var_os("HOME").map(PathBuf::from)?;
            let directory = home
                .join("Library")
                .join("Application Support")
                .join(crate::APP_NAMESPACE)
                .join("zsh-integration");
            fs::create_dir_all(&directory).ok()?;
            fs::write(directory.join(".zshenv"), ZSHENV).ok()?;
            fs::write(directory.join(".zprofile"), ZPROFILE).ok()?;
            fs::write(directory.join(".zshrc"), ZSHRC).ok()?;
            Some(directory)
        })
        .clone()
}

/// `${__WATER_USER_ZDOTDIR}` is the user's real ZDOTDIR (or HOME) captured
/// by `child_environment`. Guards are process-local (never exported) so a
/// nested shell re-runs the chain cleanly instead of inheriting "already
/// sourced" flags.
const ZSHENV: &str = r#"# water zsh integration (regenerated by Water; opt out with WATER_NO_SHELL_INTEGRATION=1)
if [[ -z ${__WATER_ZSHENV_SOURCED+set} ]]; then
  __WATER_ZSHENV_SOURCED=1
  __water_zdotdir_saved=$ZDOTDIR
  export ZDOTDIR="${__WATER_USER_ZDOTDIR:-$HOME}"
  [[ -r "$ZDOTDIR/.zshenv" ]] && source "$ZDOTDIR/.zshenv"
  if [[ $ZDOTDIR != "$__water_zdotdir_saved" ]]; then
    # The user's .zshenv redirects ZDOTDIR; follow it for later stages.
    export __WATER_USER_ZDOTDIR=$ZDOTDIR
  fi
  export ZDOTDIR="$__water_zdotdir_saved"
fi
"#;

const ZPROFILE: &str = r#"# water zsh integration
if [[ -z ${__WATER_ZPROFILE_SOURCED+set} ]]; then
  __WATER_ZPROFILE_SOURCED=1
  __water_zdotdir_saved=$ZDOTDIR
  export ZDOTDIR="${__WATER_USER_ZDOTDIR:-$HOME}"
  [[ -r "$ZDOTDIR/.zprofile" ]] && source "$ZDOTDIR/.zprofile"
  export ZDOTDIR="$__water_zdotdir_saved"
fi
"#;

const ZSHRC: &str = r#"# water zsh integration
if [[ -z ${__WATER_ZSHRC_SOURCED+set} ]]; then
  __WATER_ZSHRC_SOURCED=1
  __water_zdotdir_saved=$ZDOTDIR
  export ZDOTDIR="${__WATER_USER_ZDOTDIR:-$HOME}"
  [[ -r "$ZDOTDIR/.zshrc" ]] && source "$ZDOTDIR/.zshrc"
  # Hand the real ZDOTDIR back for the rest of the session (later stages
  # such as .zlogin and any nested shell then start without this chain).
  export ZDOTDIR="${__WATER_USER_ZDOTDIR:-$HOME}"
fi
if [[ -o interactive ]] && (( ! $+functions[clear] )); then
  # Keep the terminal's standard Ctrl-L (terminfo `clear`: screen into
  # scrollback, prompt to the top) intact and extend the `clear` command
  # itself with CSI 3 J (erase scrollback), the kitty-style split. A
  # user-defined clear() takes precedence over this wrapper.
  clear() {
    command clear "$@"
    local __water_clear_status=$?
    (( __water_clear_status == 0 )) && [[ -t 1 ]] && printf '\033[3J'
    return $__water_clear_status
  }
fi
"#;
